# Project information
site_name: 'AndKaiju'
site_description: 'Information about AndKaiju'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/AndKaiju/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007'

# Copyright
copyright: '&#127279; 2019 GNU General Public License v3.0'

# Navigation Menu
nav:
    - Home: 'index.md'
    - Usage: 'usage.md'
    - Android Debug Bridge (adb): 'adb.md'

# Configuration
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'amber'
    logo:
        icon: 'people_alt'
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Customization
extra:
    social:
        - type: 'github'
          link: 'https://github.com/rowland007'
        - type: 'twitter'
          link: 'https://twitter.com/randarxj7'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/randall-rowland-332a5039'
        - type: 'reddit-alien'
          link: 'https://www.reddit.com/user/rowland007'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
